version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-list-aws"
<<<<<<< HEAD
<<<<<<< HEAD
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12los52lhwt11"
=======
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12los52lhwt11" #Incluir bucket propio
>>>>>>> feature
=======
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12los52lhwt11" #Incluir bucket propio
>>>>>>> 4884b3bfbc0a34440cfa5062f4e42b539e854ac1
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"default\""
image_repositories = []
confirm_changeset = true

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "todo-list-aws-staging"
<<<<<<< HEAD
<<<<<<< HEAD
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12los52lhwt11"
=======
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12los52lhwt11" #Incluir bucket propio
>>>>>>> feature
=======
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12los52lhwt11" #Incluir bucket propio
>>>>>>> 4884b3bfbc0a34440cfa5062f4e42b539e854ac1
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "todo-list-aws-production"
<<<<<<< HEAD
<<<<<<< HEAD
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12los52lhwt11" 
=======
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12los52lhwt11" #Incluir bucket propio
>>>>>>> feature
=======
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12los52lhwt11" #Incluir bucket propio
>>>>>>> 4884b3bfbc0a34440cfa5062f4e42b539e854ac1
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
image_repositories = []
